// <auto-generated />
using BDHCase.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BDHCase.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220314094536_fakeData")]
    partial class fakeData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BDHCase.Domain.models.Calisan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CalismaTipi")
                        .HasColumnType("int");

                    b.Property<int>("GunlukMesai")
                        .HasColumnType("int");

                    b.Property<int>("SaatlikMesai")
                        .HasColumnType("int");

                    b.Property<float>("SaatlikMesaiUcreti")
                        .HasColumnType("real");

                    b.Property<float>("SabitUcret")
                        .HasColumnType("real");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("gunlukMesaiUcreti")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Calisanlar");

                    b.HasData(
                        new
                        {
                            Id = "0e6ba92b-f687-4f4d-9ec1-cebaf332738a",
                            Ad = "Eren",
                            CalismaTipi = 1,
                            GunlukMesai = 0,
                            SaatlikMesai = 0,
                            SaatlikMesaiUcreti = 0f,
                            SabitUcret = 7500f,
                            Soyad = "Baba",
                            TC = "1234567890",
                            gunlukMesaiUcreti = 0f
                        },
                        new
                        {
                            Id = "5f5e5f30-987a-4571-ab45-940f6cc04500",
                            Ad = "Gunluk",
                            CalismaTipi = 2,
                            GunlukMesai = 5,
                            SaatlikMesai = 0,
                            SaatlikMesaiUcreti = 0f,
                            SabitUcret = 0f,
                            Soyad = "Ucretli",
                            TC = "9876543210",
                            gunlukMesaiUcreti = 200f
                        },
                        new
                        {
                            Id = "98016e58-e2aa-499f-ae79-53e4a614f4b4",
                            Ad = "Mesai",
                            CalismaTipi = 3,
                            GunlukMesai = 0,
                            SaatlikMesai = 5,
                            SaatlikMesaiUcreti = 50f,
                            SabitUcret = 7500f,
                            Soyad = "Ucretli",
                            TC = "7894561230",
                            gunlukMesaiUcreti = 0f
                        });
                });

            modelBuilder.Entity("BDHCase.Domain.models.CalisanView", b =>
                {
                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Maas")
                        .HasColumnType("real");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tc")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("GetBordro");
                });
#pragma warning restore 612, 618
        }
    }
}
