// <auto-generated />
using BDHCase.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BDHCase.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BDHCase.Domain.models.Calisan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CalismaTipi")
                        .HasColumnType("int");

                    b.Property<int>("GunlukMesai")
                        .HasColumnType("int");

                    b.Property<float>("Maas")
                        .HasColumnType("real");

                    b.Property<int>("SaatlikMesai")
                        .HasColumnType("int");

                    b.Property<float>("SaatlikMesaiUcreti")
                        .HasColumnType("real");

                    b.Property<float>("SabitUcret")
                        .HasColumnType("real");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("gunlukMesaiUcreti")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Calisanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
